version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend/todo
    ports:
      - "5173:5173"
    depends_on:
      - backend
